### ISSUE TITLE
Scroll to selected Date or Default date

### ISSUE THREAD

**Issue by usmankhan1990** [tejpratap46/RecyclerCalendarAndroid#6]
Hi,

I am making a Vertical calendar, where I want to show my Selected date. For example if I am passing a value of 20 Feb 2021, then the scroll position should be on Feb Calendar. 12 Previous months (Start Calendar) and 12 Plus Months (End Calendar).

Please help me out, how I can should my selected Date at the time of Calendar Setup and the scroll position should be on that state also.

**Comment by tejpratap46** [comment]
Every calendar View is basically a RecyclerView, we can just use inbuilt methods to scroll. But this library do not store Position against date.
As your use case is simple (just need to scroll to middle position), you can simply use this:

```kotlin
calenderView!!.scrollToPosition(calenderView!!.adapter!!.itemCount / 2)
```

Also, If you are using `SimpleRecyclerCalendarView`, you should not pass this large date span (24 Months), performance in low end devices will be bad.
You should either consider decreasing span to 12 months or create custom calendar adapter like `InfiniteRecyclerCalenderAdapter`
For such cases take a look at [InfiniteRecyclerCalenderAdapter](https://github.com/tejpratap46/RecyclerCalendarAndroid/blob/master/recyclercalendar/src/main/java/com/tejpratapsingh/recyclercalendar/adapter/InfiniteRecyclerCalenderAdapter.kt), it also had Selection Options just like [SimpleRecyclerCalendarAdapter](https://github.com/tejpratap46/RecyclerCalendarAndroid/blob/master/recyclercalendar/src/main/java/com/tejpratapsingh/recyclercalendar/adapter/SimpleRecyclerCalendarAdapter.kt) but had to remove it. Because Calling `notifyDataSetChanged()` after every selection causes all sub calendars to flicker.

In future, i will look into possibilities of adding API to scroll to date (if possible).
